project:
  type: website
  output-dir: docs

website:
  title: "Jieming You"
  navbar:
    title: "jieming.me"
    background: "light"
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: flatly
    css: styles.css
    toc: true



