project:
  type: website
  output-dir: docs

website:
  title: "Jieming You"

  navbar:
    title: Jieming You
    background: light
    foreground: dark
    collapse: false
    #left:
      #- text: Jieming You
      #  href: index.qmd
      #- text: Photography
      #  href: http://jieming.portfoliobox.net

    right:
      - icon: instagram
        href: https://www.instagram.com/jiemingy/
      - icon: github
        href: https://github.com/jiemingyou
      - icon: linkedin
        href: http://linkedin.com/in/jiemingy/

format:
  html:
    theme: cosmos
    css: styles.css
    toc: true



